if(typeof(require) !== "undefined"){
	//turrets
	require("turrets/fallout");
	require("turrets/calamity");
	require("turrets/calamityii");
	require("turrets/mirage");
	require("turrets/illusion");
	require("turrets/ghost");
	require("turrets/shotgun");
	require("turrets/railgun");
	require("turrets/railgunii");
	require("turrets/point-defence");
	require("turrets/point-defence-ii");
	require("turrets/static");
	require("turrets/arccaster");
	require("turrets/arcstorm");
	require("turrets/eclipse");
	require("turrets/elec");
	require("turrets/phot");
	require("turrets/prot");
	require("turrets/neut");
	require("turrets/grvt");
	require("turrets/gluon");
	require("turrets/singularity");
	require("turrets/bosonw");
	require("turrets/bosonz");
	require("turrets/bosonhiggs");
	require("turrets/excalibur");
	require("turrets/neptune");
	require("turrets/spectra");
	require("turrets/rainbow");
	require("turrets/prism");
	require("turrets/refract");
	require("turrets/xenon");
	require("turrets/crusader");
	require("turrets/fahr");
	require("turrets/kelv");
	require("turrets/cels");
	require("turrets/fuseii");
	require("turrets/fuseiii");
	require("turrets/shatterf");
	require("turrets/quakef");
	require("turrets/cycloneii");
	require("turrets/typhn");
	require("turrets/cube");
	require("turrets/endgame");
	require("turrets/kamib");
	//walls
	require("advancewall");
	//power
	require("battery");
	//crafting
	require("coolant");
	require("acompressor");
	require("fission");
	require("fus");
	require("synth");
	require("fissionmkii");
	//mech
	require("blad");
	require("claymre");
	require("strdust");
	require("solar");
	require("overgrowth");
	//unit
	require("strider");
	require("angel");
	require("empunit");
	require("pestilence");
	require("famine");
	require("death");
	require("war");
	//etc
	require("rturret");
	require("effectlib");
	require("funclib");
	
	//require("turrets/singularity");
	//require("turrets/shatterf");
	//require("turrets/quakef");
}